#!/bin/sh

image_file="/run/initramfs/image-bios"

if [ ! -f "${image_file}" ];then
	echo "bios image file is not exist"
	exit
fi

function update() {
  if [ -e "/dev/mtd/bios" ];then
    echo 1e630000.spi > /sys/bus/platform/drivers/aspeed-smc/unbind
	  echo -n pass-through > /sys/bus/platform/drivers/aspeed-hardware-strap/1e6e2070.hwstrap/spi-mode
  fi
  echo -n master > /sys/bus/platform/drivers/aspeed-hardware-strap/1e6e2070.hwstrap/spi-mode
	echo 1e630000.spi > /sys/bus/platform/drivers/aspeed-smc/bind
	flashcp ${image_file} /dev/mtd/bios
	echo 1e630000.spi > /sys/bus/platform/drivers/aspeed-smc/unbind
	echo -n pass-through > /sys/bus/platform/drivers/aspeed-hardware-strap/1e6e2070.hwstrap/spi-mode
}

update
